Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 3000, host: 3000
  
  config.vm.provision "shell", inline: <<-SHELL

    apt-get update
    apt-get upgrade
  
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    rm packages-microsoft-prod.deb
    sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0
	
	dotnet add package LibsLab5 --version 1.0.0 --source http://192.168.0.103:5555/v3/index.json

	sudo apt-get install -y git
	git clone https://github.com/stas-di55ik/CrossPlatformProgrammingLabs.git
	cd CrossPlatformProgrammingLabs/Lab5WebApp
	dotnet build
	dotnet run
  SHELL
  
end