Vagrant.configure("2") do |config|
  
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.box_check_update = false

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -OutFile dotnet-sdk-installer.exe https://download.visualstudio.microsoft.com/download/pr/xxx/xxx/dotnet-sdk-xxx-win-x64.exe
    Start-Process -Wait -FilePath .\dotnet-sdk-installer.exe
    Remove-Item dotnet-sdk-installer.exe
    
    dotnet tool install --global --version 1.0.0 --add-source http://192.168.0.103:5555/v3/index.json --no-cache CPP_Lab4
  SHELL
end